language: php

php: 5.4

before_script:
    - sudo apt-get install pear php5-dev libdbus-1-dev libxml2-dev
    - sudo pear config-set auto_discover 1
    - sudo pecl install channel://pecl.php.net/dbus-0.1.1
    - composer install --dev

script: ./bin/phpspec run -fpretty
